apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd      
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
     containers:
     - name: nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nginxappsvc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 8080
  type: "NodePort"